### ISSUE TITLE
Fix the HackerEarth API

### ISSUE THREAD

**Issue by Aman-Codes** [Aman-Codes/pennamechooser#2]
**Describe the bug**
Fix the HackerEarth API as it always shows penname is no longer available even if it is available. Update the backend API code accordingly.

**To Reproduce**
Enter any username and hit enter. The HackerEarth API always fails.

**Expected behavior**
All the APIs displayed should be working properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/54680709/193418852-abae44d0-e84f-4367-99c4-6826f461ec9e.png)

**Comment by IanFindlay** [comment]
I think I see where this is failing and would like to work on this.

**Comment by IanFindlay** [comment]
Wasn't what I thought was happening but the problem is that even though it displays a 404 page HackerEarth sends it with a 200 status so the 404 status means there's no one with that username logic doesn't work. Still working on this trying to come up with a way around it but I am open to suggestions.
